---
- hosts: all

  tasks:
  - name: run mvn
    shell: "cd spring-petclinic"

  tasks:
  - name: run mvn
    shell: "./mvnw package"

  tasks:
  - name: start spring
    shell: java -jar target/*.jar

